[touch-gestures]
description = "Touch gestures"
version = "0.3.0"
author = "horriblename"

[touch-gestures.build]
output = "build/src/libtouch-gestures.so"
steps = [
    "meson setup build",
    "ninja -C build",
]
