[hyprgrass]
description = "Touch gestures"
author = "horriblename"

[hyprgrass.build]
output = "build/src/libhyprgrass.so"
steps = [
    "meson setup build",
    "ninja -C build",
]

[hyprgrass-pulse]
description = "Hyprgras extension to control audio volume in pulse-audio"
author = "horriblename"

[hyprgrass-pulse]
output = "examples/hyprgrass-pulse/build/examples/hyprgrass-pulse/libhyprgrass-pulse.so"
steps = [
    "meson setup examples/hyprgrass-pulse/build -Dhyprgrass=false -Dhyprgrass-pulse=true",
    "ninja -C examples/hyprgrass-pulse/build",
]

[hyprgrass-backlight]
description = "Hyprgras extension to control brightness of backlight"
author = "horriblename"

[hyprgrass-backlight]
output = "examples/hyprgrass-backlight/build/examples/hyprgrass-backlight/libhyprgrass-backlight.so"
steps = [
    "meson setup examples/hyprgrass-backlight/build -Dhyprgrass=false -Dhyprgrass-backlight=true -Dlogin-proxy=true",
    "ninja -C examples/hyprgrass-backlight/build",
]
