#!/bin/sh

## Usage
## -----
## Prints the tag name of the latest Hyprland release

# if anyone knows jq help me rewrite this
gh release list --repo hyprwm/Hyprland --json tagName,isLatest | \
    nix eval --impure --raw --expr 'with builtins; (head (filter (x: x.isLatest) (fromJSON (readFile /dev/stdin)))).tagName'
