name: "Nix build test"
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: horriblename
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build and test hyprgrass
        run: |
          nix build .#hyprgrassWithTests \
          --option extra-substituters https://hyprland.cachix.org \
          --option extra-trusted-public-keys hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
      - name: build hyprgrass-pulse
        run: |
          nix build .#hyprgrass-pulse \
          --option extra-substituters https://hyprland.cachix.org \
          --option extra-trusted-public-keys hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
      - name: build hyprgrass-backlight
        run: |
          nix build .#hyprgrass-backlight \
          --option extra-substituters https://hyprland.cachix.org \
          --option extra-trusted-public-keys hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
